#!/usr/bin/env python3
"""
UADIV -- identifying-field diversity check.

Tests whether AIT-ADS attack/benign separability and our own collections'
benign narrowness share one root cause: each class was generated by a
handful of tool invocations, so within-class diversity in identifying
fields (User-Agent first, then others) is near-zero, and cross-class
overlap in those values is near-zero -- making separation trivial
regardless of platform or labelling method.

Streams raw sources once each; only lightweight per-record fields
(rule_id/signature, label, extracted UA/other-field string) are kept in
memory -- not full raw records -- to stay within memory budget for the
2.6M-alert Wazuh stream.
"""
import glob
import json
import re
import sys
import os as _os
REPO_ROOT = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
from collections import Counter

import numpy as np
import pandas as pd

sys.path.insert(0, REPO_ROOT)

RAW_DIR = _os.path.join(REPO_ROOT, "data", "ait_ads", "raw")
LABELS_CSV = _os.path.join(REPO_ROOT, "data", "ait_ads", "labels.csv")

APACHE_RE = re.compile(
    r'^(?:\S+\s+)?(?P<ip>\S+) \S+ \S+ \[(?P<ts>[^\]]+)\] '
    r'"(?P<method>\S+)(?:\s+(?P<path>\S+)\s+(?P<proto>\S+))?" '
    r'(?P<status>\d+) (?P<size>\S+) "(?P<referrer>[^"]*)" "(?P<ua>[^"]*)"'
)


def norm_entropy(counter):
    """Shannon entropy of the value distribution, normalized by log2(n
    distinct values) so it lies in [0,1] regardless of alphabet size --
    stated explicitly since this project has had incompatible entropy/MI
    conventions before (see xdet_results.md's NMI convention note)."""
    total = sum(counter.values())
    if total == 0 or len(counter) <= 1:
        return 0.0
    probs = np.array([c / total for c in counter.values()])
    h = -np.sum(probs * np.log2(probs))
    h_max = np.log2(len(counter))
    return float(h / h_max) if h_max > 0 else 0.0


def class_stats(counter_attack, counter_benign, n_attack_total, n_benign_total, field_name):
    """Full Task 2 stat block for one field on one population."""
    out = {"field": field_name}
    for cls_name, counter, n_total in [("attack", counter_attack, n_attack_total),
                                        ("benign", counter_benign, n_benign_total)]:
        n_with_field = sum(counter.values())
        top = counter.most_common(3)
        top1_share = (top[0][1] / n_with_field) if top and n_with_field else 0.0
        top3_share = (sum(c for _, c in top) / n_with_field) if n_with_field else 0.0
        out[cls_name] = dict(
            n_total=n_total, n_with_field=n_with_field,
            field_coverage_pct=100 * n_with_field / n_total if n_total else float("nan"),
            n_distinct=len(counter),
            top1_share=top1_share, top3_share=top3_share,
            norm_entropy=norm_entropy(counter),
            top_values=[(str(v), c) for v, c in counter.most_common(5)],
        )
    # cross-class overlap (Task 2f)
    set_a = set(counter_attack.keys())
    set_b = set(counter_benign.keys())
    shared = set_a & set_b
    vol_a_total = sum(counter_attack.values())
    vol_b_total = sum(counter_benign.values())
    vol_a_shared = sum(counter_attack[v] for v in shared)
    vol_b_shared = sum(counter_benign[v] for v in shared)
    out["overlap"] = dict(
        n_shared_values=len(shared),
        n_distinct_attack=len(set_a), n_distinct_benign=len(set_b),
        attack_volume_in_shared_pct=100 * vol_a_shared / vol_a_total if vol_a_total else float("nan"),
        benign_volume_in_shared_pct=100 * vol_b_shared / vol_b_total if vol_b_total else float("nan"),
        shared_values_sample=[str(v) for v in list(shared)[:10]],
    )
    return out


def label_wazuh_stream():
    """Single pass over all *_wazuh.json: extract rule_id, label (via
    labels.csv), and UA (regex on full_log for native rules; structured
    data.http.http_user_agent for rule 86601). Also src_ip and url/path
    for Task 3."""
    labels = pd.read_csv(LABELS_CSV)
    files = sorted(glob.glob(f"{RAW_DIR}/*_wazuh.json"))

    all_eps, all_scn, all_rid = [], [], []
    all_ua, all_srcip, all_url = [], [], []

    for fp in files:
        scenario = fp.split("/")[-1].replace("_wazuh.json", "")
        with open(fp, errors="ignore") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                a = json.loads(line)
                ts = a.get("@timestamp")
                epoch = pd.Timestamp(ts).timestamp() if ts else np.nan
                rule = a.get("rule") or {}
                rid = rule.get("id")
                data = a.get("data") or {}
                srcip = data.get("srcip") or data.get("src_ip")
                url = data.get("url") or (data.get("http") or {}).get("url")

                ua = None
                if rid == "86601":
                    ua = (data.get("http") or {}).get("http_user_agent")
                else:
                    full_log = a.get("full_log")
                    if full_log:
                        m = APACHE_RE.match(full_log)
                        if m:
                            ua = m.group("ua")

                all_eps.append(epoch)
                all_scn.append(scenario)
                all_rid.append(rid)
                all_ua.append(ua)
                all_srcip.append(srcip)
                all_url.append(url)

    n = len(all_eps)
    print(f"Wazuh stream: {n:,} alerts read", flush=True)

    df = pd.DataFrame({"epoch": all_eps, "scenario": all_scn, "rid": all_rid,
                        "ua": all_ua, "srcip": all_srcip, "url": all_url})
    df["label"] = 0
    for scenario, wins in labels.groupby("scenario"):
        mask = df["scenario"] == scenario
        if not mask.any():
            continue
        sub = df.loc[mask, ["epoch"]].copy().reset_index()
        sub = sub.sort_values("epoch")
        w = wins.sort_values("start")[["start", "end"]].reset_index(drop=True)
        merged = pd.merge_asof(sub, w.rename(columns={"start": "epoch"}), on="epoch", direction="backward")
        is_attack = (merged["epoch"] <= merged["end"]) & merged["end"].notna()
        idx = merged.loc[is_attack.values, "index"].values
        df.loc[idx, "label"] = 1

    return df


def label_aminer_stream():
    files = sorted(glob.glob(f"{RAW_DIR}/*_aminer.json"))
    labels = pd.read_csv(LABELS_CSV)
    all_eps, all_scn, all_ua, all_srcip, all_path = [], [], [], [], []

    for fp in files:
        scenario = fp.split("/")[-1].replace("_aminer.json", "")
        with open(fp, errors="ignore") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                a = json.loads(line)
                ld = a.get("LogData") or {}
                dt = (ld.get("DetectionTimestamp") or [None])[0]
                raw = (ld.get("RawLogData") or [None])[0]
                ua, srcip, path = None, None, None
                if raw:
                    m = APACHE_RE.match(raw)
                    if m:
                        ua = m.group("ua")
                        srcip = m.group("ip")
                        path = m.group("path")
                all_eps.append(float(dt) if dt else np.nan)
                all_scn.append(scenario)
                all_ua.append(ua)
                all_srcip.append(srcip)
                all_path.append(path)

    n = len(all_eps)
    print(f"AMiner stream: {n:,} alerts read", flush=True)
    df = pd.DataFrame({"epoch": all_eps, "scenario": all_scn, "ua": all_ua,
                        "srcip": all_srcip, "path": all_path})
    df["label"] = 0
    for scenario, wins in labels.groupby("scenario"):
        mask = df["scenario"] == scenario
        if not mask.any():
            continue
        sub = df.loc[mask, ["epoch"]].copy().reset_index()
        sub = sub.sort_values("epoch")
        w = wins.sort_values("start")[["start", "end"]].reset_index(drop=True)
        merged = pd.merge_asof(sub, w.rename(columns={"start": "epoch"}), on="epoch", direction="backward")
        is_attack = (merged["epoch"] <= merged["end"]) & merged["end"].notna()
        idx = merged.loc[is_attack.values, "index"].values
        df.loc[idx, "label"] = 1
    return df


def main():
    results = {}

    print("=" * 70, "\nStreaming AIT-ADS Wazuh...\n", "=" * 70)
    wz = label_wazuh_stream()
    native = wz[wz.rid != "86601"]
    suri = wz[wz.rid == "86601"]

    print("=" * 70, "\nStreaming AIT-ADS AMiner...\n", "=" * 70)
    am = label_aminer_stream()

    print("=" * 70, "\nLoading our Linux/Windows collections...\n", "=" * 70)
    lnx_attack = pd.read_csv(_os.path.join(REPO_ROOT, "data", "testbed_collection", "labeled_lnx.csv"))
    lnx_attack = lnx_attack[lnx_attack.label == "attack"].copy()
    lnx_attack["ua"] = lnx_attack["full_log"].apply(
        lambda s: (APACHE_RE.match(s).group("ua") if isinstance(s, str) and APACHE_RE.match(s) else None))

    lnx_benign_recs = []
    with open(_os.path.join(REPO_ROOT, "data", "testbed_collection", "collection_benign_lnx_alerts.json")) as f:
        for line in f:
            lnx_benign_recs.append(json.loads(line))
    lnx_benign = pd.DataFrame(lnx_benign_recs)
    lnx_benign["ua"] = lnx_benign["full_log"].apply(
        lambda s: (APACHE_RE.match(s).group("ua") if isinstance(s, str) and APACHE_RE.match(s) else None))

    win_attack = pd.read_csv(_os.path.join(REPO_ROOT, "data", "testbed_collection", "labeled_win.csv"))
    win_attack = win_attack[win_attack.label == "attack"].copy()
    win_attack["ua"] = None  # no full_log / HTTP field in Sysmon-based Windows collection

    win_benign_recs = []
    with open(_os.path.join(REPO_ROOT, "data", "testbed_collection", "collection_benign_win_alerts.json")) as f:
        for line in f:
            win_benign_recs.append(json.loads(line))
    win_benign = pd.DataFrame(win_benign_recs)
    win_benign["ua"] = None

    # ================= TASK 1: field coverage =================
    print("\n" + "=" * 70 + "\nTASK 1 -- User-Agent field coverage\n" + "=" * 70)
    coverage = {}
    for name, df_pop, col in [
        ("AIT-ADS Wazuh-native", native, "ua"),
        ("AIT-ADS Suricata (86601)", suri, "ua"),
        ("AIT-ADS AMiner", am, "ua"),
        ("Our Linux attack", lnx_attack, "ua"),
        ("Our Linux benign", lnx_benign, "ua"),
        ("Our Windows attack", win_attack, "ua"),
        ("Our Windows benign", win_benign, "ua"),
    ]:
        n = len(df_pop)
        n_ua = df_pop[col].notna().sum()
        pct = 100 * n_ua / n if n else float("nan")
        print(f"  {name:28s} n={n:>10,}  with UA={n_ua:>10,}  coverage={pct:.2f}%")
        coverage[name] = dict(n=int(n), n_with_ua=int(n_ua), coverage_pct=float(pct))
    results["task1_coverage"] = coverage

    # ================= TASK 2: diversity per class =================
    print("\n" + "=" * 70 + "\nTASK 2 -- Diversity per class (UA), populations with usable coverage\n" + "=" * 70)
    task2 = {}

    def ua_counters(df_pop):
        atk = Counter(df_pop.loc[df_pop.label == 1, "ua"].dropna())
        ben = Counter(df_pop.loc[df_pop.label == 0, "ua"].dropna())
        n_atk = int((df_pop.label == 1).sum())
        n_ben = int((df_pop.label == 0).sum())
        return atk, ben, n_atk, n_ben

    for name, df_pop in [
        ("AIT-ADS Wazuh-native", native),
        ("AIT-ADS Suricata (86601)", suri),
        ("AIT-ADS AMiner", am),
    ]:
        atk_c, ben_c, n_atk, n_ben = ua_counters(df_pop)
        stat = class_stats(atk_c, ben_c, n_atk, n_ben, "user_agent")
        task2[name] = stat
        print(f"\n  {name}:")
        print(f"    attack: n_with_ua={stat['attack']['n_with_field']:,} distinct={stat['attack']['n_distinct']} "
              f"top1={stat['attack']['top1_share']:.4f} top3={stat['attack']['top3_share']:.4f} "
              f"H_norm={stat['attack']['norm_entropy']:.4f}")
        print(f"    benign: n_with_ua={stat['benign']['n_with_field']:,} distinct={stat['benign']['n_distinct']} "
              f"top1={stat['benign']['top1_share']:.4f} top3={stat['benign']['top3_share']:.4f} "
              f"H_norm={stat['benign']['norm_entropy']:.4f}")
        print(f"    overlap: {stat['overlap']['n_shared_values']} shared values / "
              f"attack_distinct={stat['overlap']['n_distinct_attack']} benign_distinct={stat['overlap']['n_distinct_benign']} "
              f"| attack_vol_in_shared={stat['overlap']['attack_volume_in_shared_pct']:.4f}% "
              f"benign_vol_in_shared={stat['overlap']['benign_volume_in_shared_pct']:.4f}%")
        print(f"    attack top values: {stat['attack']['top_values']}")
        print(f"    benign top values: {stat['benign']['top_values']}")

    # our Linux: attack (labeled_lnx.csv) vs benign (collection_benign_lnx_alerts.json)
    atk_c = Counter(lnx_attack["ua"].dropna())
    ben_c = Counter(lnx_benign["ua"].dropna())
    stat = class_stats(atk_c, ben_c, len(lnx_attack), len(lnx_benign), "user_agent")
    task2["Our Linux (attack vs benign collections)"] = stat
    print(f"\n  Our Linux (attack collection vs benign collection):")
    print(f"    attack top values: {stat['attack']['top_values']}")
    print(f"    benign top values: {stat['benign']['top_values']}")
    print(f"    overlap: {stat['overlap']}")

    results["task2_diversity"] = task2

    # ================= TASK 3: other identifying fields =================
    print("\n" + "=" * 70 + "\nTASK 3 -- other identifying fields\n" + "=" * 70)
    task3 = {}

    # AIT-ADS Wazuh-native: srcip, url
    for field in ["srcip", "url"]:
        atk_c = Counter(native.loc[native.label == 1, field].dropna())
        ben_c = Counter(native.loc[native.label == 0, field].dropna())
        n_atk = int((native.label == 1).sum())
        n_ben = int((native.label == 0).sum())
        stat = class_stats(atk_c, ben_c, n_atk, n_ben, field)
        task3.setdefault("AIT-ADS Wazuh-native", {})[field] = stat
        print(f"  Wazuh-native / {field}: attack distinct={stat['attack']['n_distinct']} "
              f"top1={stat['attack']['top1_share']:.4f} | benign distinct={stat['benign']['n_distinct']} "
              f"top1={stat['benign']['top1_share']:.4f} | shared={stat['overlap']['n_shared_values']}")

    # AIT-ADS Suricata: srcip
    atk_c = Counter(suri.loc[suri.label == 1, "srcip"].dropna())
    ben_c = Counter(suri.loc[suri.label == 0, "srcip"].dropna())
    stat = class_stats(atk_c, ben_c, int((suri.label==1).sum()), int((suri.label==0).sum()), "srcip")
    task3.setdefault("AIT-ADS Suricata (86601)", {})["srcip"] = stat
    print(f"  Suricata / srcip: attack distinct={stat['attack']['n_distinct']} top1={stat['attack']['top1_share']:.4f} "
          f"| benign distinct={stat['benign']['n_distinct']} top1={stat['benign']['top1_share']:.4f} "
          f"| shared={stat['overlap']['n_shared_values']}")

    # AIT-ADS AMiner: srcip, path
    for field in ["srcip", "path"]:
        atk_c = Counter(am.loc[am.label == 1, field].dropna())
        ben_c = Counter(am.loc[am.label == 0, field].dropna())
        n_atk = int((am.label == 1).sum())
        n_ben = int((am.label == 0).sum())
        stat = class_stats(atk_c, ben_c, n_atk, n_ben, field)
        task3.setdefault("AIT-ADS AMiner", {})[field] = stat
        print(f"  AMiner / {field}: attack distinct={stat['attack']['n_distinct']} top1={stat['attack']['top1_share']:.4f} "
              f"| benign distinct={stat['benign']['n_distinct']} top1={stat['benign']['top1_share']:.4f} "
              f"| shared={stat['overlap']['n_shared_values']}")

    # our Linux: srcip (previously established), srcuser
    print(f"\n  Our Linux collections (previously established srcip note + new srcuser check):")
    lnx_attack_full = pd.read_csv(_os.path.join(REPO_ROOT, "data", "testbed_collection", "labeled_lnx.csv"))
    lnx_attack_full = lnx_attack_full[lnx_attack_full.label == "attack"]
    print(f"    srcip: attack distinct={lnx_attack_full['srcip'].nunique()} "
          f"(PREVIOUSLY ESTABLISHED degenerate, ew_phase0_inventory.md: single value 127.0.0.1)")
    print(f"    srcuser: attack distinct={lnx_attack_full['srcuser'].nunique()} "
          f"null%={lnx_attack_full['srcuser'].isna().mean()*100:.1f}%")

    # our Windows: image/parent_image/target_user
    win_attack_full = pd.read_csv(_os.path.join(REPO_ROOT, "data", "testbed_collection", "labeled_win.csv"))
    win_attack_full = win_attack_full[win_attack_full.label == "attack"]
    print(f"\n  Our Windows attack collection:")
    print(f"    image: distinct={win_attack_full['image'].nunique()} -> {win_attack_full['image'].value_counts().to_dict()}")
    print(f"    parent_image: distinct={win_attack_full['parent_image'].nunique()} -> {win_attack_full['parent_image'].value_counts().to_dict()}")
    print(f"    target_user: distinct={win_attack_full['target_user'].nunique()}")

    def jsonable(o):
        if isinstance(o, dict):
            return {str(k): jsonable(v) for k, v in o.items()}
        if isinstance(o, list):
            return [jsonable(v) for v in o]
        if isinstance(o, tuple):
            return [jsonable(v) for v in o]
        if isinstance(o, (np.integer,)):
            return int(o)
        if isinstance(o, (np.floating,)):
            return float(o)
        if isinstance(o, (np.bool_,)):
            return bool(o)
        return o

    results["task3_other_fields"] = task3
    out_path = _os.path.join(REPO_ROOT, "analysis", "uadiv_results.json")
    with open(out_path, "w") as f:
        json.dump(jsonable(results), f, indent=2)
    print(f"\nSaved {out_path}")


if __name__ == "__main__":
    main()
